#!/usr/bin/env bash

# Transfers a file from our client to a server using SCP (Secure Copy Protocol).
#
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#   PATH_TO_FILE: The path to the file to be transferred.
#   IP: The IP address of the server we want to transfer the file to.
#   USERNAME: The username scp connects with on the server.
#   PATH_TO_SSH_KEY: The path to the SSH private key that scp uses for authentication.

# Check if all required parameters are provided.
if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ "$#" -lt 4 ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
