#!/usr/bin/env bash
# Script to install and configure a load balancer

echo -e "Updating and doing some minor checks...\n"

# Function to install packages if not already installed
function install() {
	command -v "$1" &> /dev/null

	# shellcheck disable=SC2181
	if [ $? -ne 0 ]; then
		echo -e "   Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

# Install haproxy
install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup default server configuration file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

# Configure Haproxy server block
server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend opokumensahpeter-tech-frontend
    bind *:80
    default_backend opokumensahpeter-tech-backend

backend opokumensahpeter-tech-backend
    balance roundrobin
    server 530428-web-01 54.167.187.16:80 check
    server 530428-web-02 54.172.159.27:80 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "configured - Roundrobin On web-01 & web-02"

# Start or restart haproxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi

echo -e "web-01 web-02"
