#!/usr/bin/env bash
# Script to setup MySQL slave server configuration

# Allow MySQL port through firewall
echo -e "*** Allowing Port ***\n"
sudo ufw allow 3306

# Disable firewall (if enabled) and then enable it
sudo ufw disable
sudo ufw enable

# Configuration data for MySQL
config_data=\
"
# The MySQL  Server configuration file.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

# The MySQL  Server configuration file.
#
# For explanations see
# http://dev.mysql.com/doc/mysql/en/server-system-variables.html

[mysqld]
binlog_do_db    = tyrell_corp
relay-log       = /var/log/mysql/mysql-relay-bin.log
log_bin         = /var/log/mysql/mysql-bin.log
server-id       = 2
pid-file        = /var/run/mysqld/mysqld.pid
socket          = /var/run/mysqld/mysqld.sock
datadir         = /var/lib/mysql
log-error       = /var/log/mysql/error.log
# By default we only accept connections from localhost
bind-address    = 127.0.0.1
# Disabling symbolic-links is recommended to prevent assorted security risks
symbolic-links=0
"

# Apply configuration data to MySQL config file
echo "$config_data" | sudo dd status=none of=/etc/mysql/mysql.conf.d/mysqld.cnf

# Restart MySQL service to apply changes
sudo systemctl restart mysql

# Confirmation message
echo -e "*** Configuration Done ***"
