#!/usr/bin/env bash
# Configures a server to listen on port 80 of all active IPv4 IPs.

# Update the Nginx configuration file to listen on port 80
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
sudo service nginx restart

# Clear the Nginx process ID file to prevent errors
echo "" | sudo dd status=none of=/run/nginx.pid
